
test: system execution failed.
Following is the set of recorded exceptions:

******************************** Thread exception *****************************
In thread           Root thread            0x0 (thread id)
*******************************************************************************
-------------------------------------------------------------------------------
Class / Object      Routine                Nature of exception           Effect
-------------------------------------------------------------------------------
PYTHON_INTERPRETER  run_program_file @2    file_exists:                 
<00000238437D05B8>                         Precondition violated.        Fail
-------------------------------------------------------------------------------
PYTHON_TEST         test_inspect_variables @7
<00000238437C6588>                         Routine failure.              Fail
-------------------------------------------------------------------------------
PYTHON_TEST         make @6                                             
<00000238437C6588>                         Routine failure.              Fail
-------------------------------------------------------------------------------
PYTHON_TEST         root's creation                                     
<00000238437C6588>                         Routine failure.              Exit
-------------------------------------------------------------------------------

test: system execution failed.
Following is the set of recorded exceptions:

******************************** Thread exception *****************************
In thread           Root thread            0x0 (thread id)
*******************************************************************************
-------------------------------------------------------------------------------
Class / Object      Routine                Nature of exception           Effect
-------------------------------------------------------------------------------
PYTHON_INTERPRETER  value @3               symbol_exists:               
<000002167E650858>                         Precondition violated.        Fail
-------------------------------------------------------------------------------
PYTHON_TEST         test_inspect_variables @11
<000002167E646588>                         Routine failure.              Fail
-------------------------------------------------------------------------------
PYTHON_TEST         make @6                                             
<000002167E646588>                         Routine failure.              Fail
-------------------------------------------------------------------------------
PYTHON_TEST         root's creation                                     
<000002167E646588>                         Routine failure.              Exit
-------------------------------------------------------------------------------
